### ISSUE TITLE
Shape mirrored after applying `.transformedShape()` after nest

### ISSUE THREAD

**Issue by hl037** [Ultimaker/pynest2d#14]
Hi,
First, thanks for this binding.

I have a very strange problem : When I do the nesting and apply `.transformedShape()` to my items, they get mirrored...

here an mwe : 

```

import pynest2d as nest

w_p, h_p = 2480, 3508
w, h = 290, 314
bin = nest.Box(w_p, h_p)
items = [
  nest.Item([
    nest.Point(0, 0),
    nest.Point(w, 0),
    nest.Point(w, h),
    nest.Point(0, h),
  ])
]
bin_count = nest.nest(items, bin)
it = items[0]
it_t = it.transformedShape()
pts = [ (it.vertex(i).x(), it.vertex(i).y()) for i in range(4) ]
pts_t = [ (it_t.vertex(i).x(), it_t.vertex(i).y()) for i in range(4) ]
print(pts)
print(pts_t)

```

I get : 

```
Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import pynest2d as nest
>>> 
>>> w_p, h_p = 2480, 3508
>>> w, h = 290, 314
>>> bin = nest.Box(w_p, h_p)
>>> items = [
...   nest.Item([
...     nest.Point(0, 0),
...     nest.Point(w, 0),
...     nest.Point(w, h),
...     nest.Point(0, h),
...   ])
... ]
>>> bin_count = nest.nest(items, bin)
>>> it = items[0]
>>> it_t = it.transformedShape()
>>> pts = [ (it.vertex(i).x(), it.vertex(i).y()) for i in range(4) ]
>>> pts_t = [ (it_t.vertex(i).x(), it_t.vertex(i).y()) for i in range(4) ]
>>> print(pts)
[(0, 0), (290, 0), (290, 314), (0, 314)]
>>> print(pts_t)
[(145, -157), (-145, -157), (-145, 157), (145, 157)]
>>> 
```

While the initial item "turns" clockwise (with x→ and y↓), the transformed one turns conter-clockwise.

It's not blocking to me if this is an expected behaviour, but it's weird, and if so, I think it should be mentioned in the readme.

My ask also is : is it consistent ? should I expect always all shape to be mirrored or is there situations where they are not ?

**Comment by Ghostkeeper** [comment]
The issue is that libnest2d (the upstream project that this project provides bindings for) holds the convention that polygons are specified in clockwise order. Now, for the input I don't think it really matters. Maybe it takes the convex hull of the shape and that fixes it. But its output will always be in clockwise order.

We didn't run into this issue since in Cura we only use the `rotation()` and `translation()` output and apply those ourselves.

So I think this is expected behaviour. And if it's not, it would be an issue with [libnest2d](https://github.com/tamasmeszaros/libnest2d) itself, rather than these Python bindings for it.
